"""
《翻身》v4 高质量剧本
三幕结构：颓废→发现→努力→翻身
"""

SCRIPT_V4 = {
    "title": "翻身",
    "subtitle": "一个职场人的AI视频创作逆袭之路",
    "duration": 180,
    "genre": "励志/产品宣传片",
    "target_platform": "抖音/视频号",
    "aspect_ratio": "9:16",

    "characters": {
        "林默": {
            "age": 32,
            "gender": "male",
            "appearance": "消瘦，黑眼圈，穿着皱巴巴的衬衫，眼神疲惫",
            "personality": "内向，有才华但缺乏自信，被职场磨平了棱角",
            "role": "主角",
        },
        "老板": {
            "age": 45,
            "gender": "male",
            "appearance": "西装革履，表情严厉",
            "personality": "功利，只看结果",
            "role": "配角",
        },
        "旁白": {
            "voice": "沉稳男声，带温度",
            "role": "叙述者",
        },
    },

    "scenes": [
        # ===== 第一幕：颓废（0-40秒）=====
        {
            "id": "S01",
            "name": "深夜加班",
            "duration": 8,
            "location": "办公室",
            "time": "深夜",
            "lighting": "冷色调，只有电脑屏幕的蓝光",
            "mood": "压抑、疲惫",
            "shots": [
                {
                    "id": "S01_01",
                    "duration": 3,
                    "shot_size": "大远景",
                    "camera_move": "缓推",
                    "description": "空旷的办公室，只有林默的工位亮着灯，他趴在键盘上",
                    "dialogue": "",
                    "narration": "凌晨两点，办公室只剩下他一个人。",
                    "sound": {"bgm": "melancholy", "sfx": ["键盘敲击声", "空调嗡嗡声"]},
                },
                {
                    "id": "S01_02",
                    "duration": 3,
                    "shot_size": "特写",
                    "camera_move": "固定",
                    "description": "电脑屏幕上是被打回的方案，红色批注密密麻麻",
                    "dialogue": "",
                    "narration": "第三十二次被打回的方案。",
                    "sound": {"bgm": "melancholy", "sfx": ["鼠标点击声"]},
                },
                {
                    "id": "S01_03",
                    "duration": 2,
                    "shot_size": "近景",
                    "camera_move": "固定",
                    "description": "林默揉着太阳穴，眼神空洞地看着屏幕",
                    "dialogue": "",
                    "narration": "他开始怀疑，自己是不是真的不行。",
                    "sound": {"bgm": "melancholy"},
                },
            ],
        },
        {
            "id": "S02",
            "name": "职场受挫",
            "duration": 10,
            "location": "会议室",
            "time": "白天",
            "lighting": "日光灯，惨白",
            "mood": "屈辱、无力",
            "shots": [
                {
                    "id": "S02_01",
                    "duration": 3,
                    "shot_size": "中景",
                    "camera_move": "固定",
                    "description": "老板把文件摔在桌上，林默低着头站在对面",
                    "dialogue": "老板：这种东西也敢拿出来？重做！",
                    "narration": "",
                    "sound": {"bgm": "tension", "sfx": ["文件摔桌声"]},
                },
                {
                    "id": "S02_02",
                    "duration": 3,
                    "shot_size": "特写",
                    "camera_move": "固定",
                    "description": "林默攥紧的拳头，指甲嵌入掌心",
                    "dialogue": "",
                    "narration": "他想反驳，却发现自己连一个能拿得出手的作品都没有。",
                    "sound": {"bgm": "tension"},
                },
                {
                    "id": "S02_03",
                    "duration": 4,
                    "shot_size": "跟拍",
                    "camera_move": "跟拍",
                    "description": "林默走出写字楼，融入下班的人潮，背影孤单",
                    "dialogue": "",
                    "narration": "三十岁，一事无成。这就是他的人生吗？",
                    "sound": {"bgm": "melancholy", "sfx": ["城市环境音"]},
                },
            ],
        },
        {
            "id": "S03",
            "name": "偶然发现",
            "duration": 12,
            "location": "出租屋",
            "time": "深夜",
            "lighting": "台灯暖光，电脑屏幕",
            "mood": "好奇、一丝希望",
            "shots": [
                {
                    "id": "S03_01",
                    "duration": 4,
                    "shot_size": "中景",
                    "camera_move": "缓推",
                    "description": "林默瘫在沙发上刷手机，突然看到一个视频",
                    "dialogue": "",
                    "narration": "直到那天晚上，他刷到了一条视频。",
                    "sound": {"bgm": "curious", "sfx": ["手机滑动声"]},
                },
                {
                    "id": "S03_02",
                    "duration": 4,
                    "shot_size": "特写",
                    "camera_move": "固定",
                    "description": "手机屏幕上是ai-video-editor的介绍：AI驱动的智能视频剪辑平台",
                    "dialogue": "",
                    "narration": "一个叫ai-video-editor的工具，号称能让普通人也能做出专业级视频。",
                    "sound": {"bgm": "curious"},
                },
                {
                    "id": "S03_03",
                    "duration": 4,
                    "shot_size": "近景",
                    "camera_move": "固定",
                    "description": "林默的眼睛慢慢亮了起来，坐直了身体",
                    "dialogue": "林默（自语）：也许...可以试试？",
                    "narration": "",
                    "sound": {"bgm": "hopeful_start"},
                },
            ],
        },

        # ===== 第二幕：发现与学习（40-100秒）=====
        {
            "id": "S04",
            "name": "初次尝试",
            "duration": 15,
            "location": "出租屋",
            "time": "深夜到凌晨",
            "lighting": "电脑屏幕光，时间流逝感",
            "mood": "兴奋、专注",
            "shots": [
                {
                    "id": "S04_01",
                    "duration": 4,
                    "shot_size": "过肩镜头",
                    "camera_move": "固定",
                    "description": "林默在电脑前打开ai-video-editor，界面简洁现代",
                    "dialogue": "",
                    "narration": "他下载了软件，开始了第一次尝试。",
                    "sound": {"bgm": "hopeful_start", "sfx": ["鼠标点击声", "键盘声"]},
                },
                {
                    "id": "S04_02",
                    "duration": 4,
                    "shot_size": "特写",
                    "camera_move": "固定",
                    "description": "屏幕上：输入一句话描述，AI自动生成剧本、分镜、素材",
                    "dialogue": "",
                    "narration": "输入一句话，AI自动写剧本、分镜、甚至生成画面素材。",
                    "sound": {"bgm": "hopeful_start"},
                },
                {
                    "id": "S04_03",
                    "duration": 3,
                    "shot_size": "近景",
                    "camera_move": "固定",
                    "description": "林默惊讶地张大嘴巴，然后露出久违的笑容",
                    "dialogue": "林默：这...这也太厉害了吧！",
                    "narration": "",
                    "sound": {"bgm": "uplifting"},
                },
                {
                    "id": "S04_04",
                    "duration": 4,
                    "shot_size": "蒙太奇",
                    "camera_move": "快切",
                    "description": "时间流逝：窗外从黑夜到天亮，林默一直在电脑前创作",
                    "dialogue": "",
                    "narration": "那一晚，他忘记了时间。",
                    "sound": {"bgm": "uplifting", "sfx": ["时钟滴答声加快"]},
                },
            ],
        },
        {
            "id": "S05",
            "name": "能力觉醒",
            "duration": 20,
            "location": "出租屋/咖啡馆",
            "time": "一周后",
            "lighting": "明亮，暖色调",
            "mood": "自信、成长",
            "shots": [
                {
                    "id": "S05_01",
                    "duration": 4,
                    "shot_size": "中景",
                    "camera_move": "缓推",
                    "description": "林默在咖啡馆用笔记本电脑剪辑视频，表情专注而自信",
                    "dialogue": "",
                    "narration": "一周后，他已经能熟练地用AI生成素材、配音、加特效。",
                    "sound": {"bgm": "uplifting", "sfx": ["咖啡馆环境音"]},
                },
                {
                    "id": "S05_02",
                    "duration": 4,
                    "shot_size": "特写",
                    "camera_move": "固定",
                    "description": "屏幕上是他做的第一条视频：画面精美，有旁白有BGM有特效",
                    "dialogue": "",
                    "narration": "第一条视频，画面精美，配音专业，特效到位。",
                    "sound": {"bgm": "uplifting"},
                },
                {
                    "id": "S05_03",
                    "duration": 4,
                    "shot_size": "近景",
                    "camera_move": "固定",
                    "description": "林默点击发布，深吸一口气",
                    "dialogue": "",
                    "narration": "他鼓起勇气，点击了发布。",
                    "sound": {"bgm": "tension", "sfx": ["鼠标点击声"]},
                },
                {
                    "id": "S05_04",
                    "duration": 4,
                    "shot_size": "特写",
                    "camera_move": "快推",
                    "description": "手机通知不断弹出：点赞100、500、1000、10000+",
                    "dialogue": "",
                    "narration": "然后，奇迹发生了。",
                    "sound": {"bgm": "triumphant", "sfx": ["通知提示音不断"]},
                },
                {
                    "id": "S05_05",
                    "duration": 4,
                    "shot_size": "近景",
                    "camera_move": "固定",
                    "description": "林默看着手机，眼眶泛红，嘴角上扬",
                    "dialogue": "林默（哽咽）：原来...我也可以。",
                    "narration": "",
                    "sound": {"bgm": "triumphant"},
                },
            ],
        },

        # ===== 第三幕：翻身（100-180秒）=====
        {
            "id": "S06",
            "name": "职场逆袭",
            "duration": 20,
            "location": "办公室/会议室",
            "time": "一个月后",
            "lighting": "明亮，暖色调",
            "mood": "自信、从容",
            "shots": [
                {
                    "id": "S06_01",
                    "duration": 4,
                    "shot_size": "中景",
                    "camera_move": "跟拍",
                    "description": "林默穿着整洁的衬衫，自信地走进办公室，同事们侧目",
                    "dialogue": "",
                    "narration": "一个月后，他像变了一个人。",
                    "sound": {"bgm": "triumphant"},
                },
                {
                    "id": "S06_02",
                    "duration": 5,
                    "shot_size": "中景",
                    "camera_move": "固定",
                    "description": "会议室里，林默演示自己做的产品宣传视频，老板和同事们惊讶地看着",
                    "dialogue": "林默：这是我用ai-video-editor做的方案，大家看一下。",
                    "narration": "",
                    "sound": {"bgm": "triumphant"},
                },
                {
                    "id": "S06_03",
                    "duration": 4,
                    "shot_size": "特写",
                    "camera_move": "固定",
                    "description": "老板惊讶的表情，然后露出赞许的笑容",
                    "dialogue": "老板：这...这是你一个人做的？",
                    "narration": "",
                    "sound": {"bgm": "triumphant"},
                },
                {
                    "id": "S06_04",
                    "duration": 4,
                    "shot_size": "近景",
                    "camera_move": "固定",
                    "description": "林默微笑着点头，眼神坚定",
                    "dialogue": "林默：是的。AI是工具，创意才是核心。",
                    "narration": "",
                    "sound": {"bgm": "triumphant"},
                },
                {
                    "id": "S06_05",
                    "duration": 3,
                    "shot_size": "全景",
                    "camera_move": "缓拉",
                    "description": "会议室里响起掌声",
                    "dialogue": "",
                    "narration": "掌声响起的那一刻，他知道，自己真的翻身了。",
                    "sound": {"bgm": "triumphant", "sfx": ["掌声"]},
                },
            ],
        },
        {
            "id": "S07",
            "name": "产品亮相",
            "duration": 25,
            "location": "创意空间",
            "time": "白天",
            "lighting": "明亮现代，科技感",
            "mood": "激励、展望",
            "shots": [
                {
                    "id": "S07_01",
                    "duration": 5,
                    "shot_size": "大远景",
                    "camera_move": "缓推",
                    "description": "现代化的创意空间，多个创作者在使用ai-video-editor工作",
                    "dialogue": "",
                    "narration": "ai-video-editor，不只是一个工具。",
                    "sound": {"bgm": "inspiring"},
                },
                {
                    "id": "S07_02",
                    "duration": 5,
                    "shot_size": "蒙太奇",
                    "camera_move": "快切",
                    "description": "快速展示：AI写剧本→自动分镜→ComfyUI出图→声音引擎→一键成片",
                    "dialogue": "",
                    "narration": "它是你的剧本顾问、分镜导演、美术指导、音效师、剪辑师。",
                    "sound": {"bgm": "inspiring", "sfx": ["科技感音效"]},
                },
                {
                    "id": "S07_03",
                    "duration": 5,
                    "shot_size": "中景",
                    "camera_move": "固定",
                    "description": "林默站在窗前，看着城市，手中端着咖啡，表情从容",
                    "dialogue": "",
                    "narration": "每个人都有创意，只是缺少一个把创意变成现实的工具。",
                    "sound": {"bgm": "inspiring"},
                },
                {
                    "id": "S07_04",
                    "duration": 5,
                    "shot_size": "特写",
                    "camera_move": "固定",
                    "description": "ai-video-editor的logo和标语：让每个人都能做出专业级视频",
                    "dialogue": "",
                    "narration": "ai-video-editor，让创意不再受限于技术。",
                    "sound": {"bgm": "inspiring"},
                },
                {
                    "id": "S07_05",
                    "duration": 5,
                    "shot_size": "全景",
                    "camera_move": "缓拉",
                    "description": "林默转身走向镜头，身后是明亮的城市天际线",
                    "dialogue": "林默：你的翻身之作，从这里开始。",
                    "narration": "",
                    "sound": {"bgm": "inspiring", "sfx": ["收尾音效"]},
                },
            ],
        },
    ],

    "emotional_arc": [
        {"time": 0, "emotion": "压抑", "intensity": 0.8},
        {"time": 30, "emotion": "屈辱", "intensity": 0.9},
        {"time": 40, "emotion": "好奇", "intensity": 0.5},
        {"time": 55, "emotion": "兴奋", "intensity": 0.7},
        {"time": 80, "emotion": "自信", "intensity": 0.8},
        {"time": 100, "emotion": "惊喜", "intensity": 0.9},
        {"time": 120, "emotion": "从容", "intensity": 0.8},
        {"time": 150, "emotion": "激励", "intensity": 0.9},
        {"time": 180, "emotion": "希望", "intensity": 1.0},
    ],
}

if __name__ == "__main__":
    import json
    print("=" * 60)
    print("《翻身》v4 高质量剧本")
    print("=" * 60)
    print(f"标题: {SCRIPT_V4['title']}")
    print(f"时长: {SCRIPT_V4['duration']}秒")
    print(f"场景数: {len(SCRIPT_V4['scenes'])}")
    total_shots = sum(len(s['shots']) for s in SCRIPT_V4['scenes'])
    print(f"镜头数: {total_shots}")
    print(f"角色: {list(SCRIPT_V4['characters'].keys())}")
    print(f"\n情绪曲线:")
    for point in SCRIPT_V4['emotional_arc']:
        print(f"  {point['time']}s: {point['emotion']} (强度{point['intensity']})")
    print("\n场景列表:")
    for scene in SCRIPT_V4['scenes']:
        print(f"  {scene['id']} {scene['name']} ({scene['duration']}s, {len(scene['shots'])}镜) - {scene['mood']}")
    print("\n✅ 剧本创作完成")
